### ISSUE TITLE
Most of the Links to Policies in the Azure Docs are now broken

### ISSUE THREAD

**Issue by scottstout** [Azure/Enterprise-Scale#125] opened 2020-07-28 19:45 UTC
The links to policies on this page are broken:

https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/implementation-guidelines#security-governance-and-compliance

It looks like the the path:
azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560/contoso/.AzState/

got changed to:
azopsreference/3fc1081d-6105-4e19-b60c-1ec1252cf560%20(3fc1081d-6105-4e19-b60c-1ec1252cf560)/contoso%20(contoso)/.AzState

**Comment by ranieuwe** [comment] 2020-07-28 20:31
Issue is caused by 28c74a8 and d8bd1af85656bb626f1eb8fab44bdc01ca6336fb. Docs got corrected in c735640e50e4d691ed8218ac8c4033a5cf5b984c but it seems these changes have not made it to the public docs site yet. I do not see a PR in @ [MicrosoftDocs/cloud-adoption-framework](https://github.com/MicrosoftDocs/cloud-adoption-framework/).

We need to make sure have permanent links to these files moving forward as they are linked to from various places. 

/cc @uday31in

**Comment by hjscherer** [comment] 2020-08-05 20:54
The links to the policy defintions have been updated. Keeping this PR open so that we can provide a major update to the implementation guide in the CAF docs.

**Comment by krowlandson** [comment] 2021-04-07 17:00
Looks like this same issue is also effecting our internal docs, such as:
https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md

**Comment by hjscherer** [comment] 2021-05-12 07:07
This has been resolved with the recent doc updates on ESLZ repo and CAF

**Closed by hjscherer** 2021-05-12 07:07 UTC
Labels: bug
