### ISSUE TITLE
Effect parameter missing in policy set definition for RecoveryVaultDeployDiagnosticLogDeployLogAnalytics 

### ISSUE THREAD

**Issue by JoshuaMcConnaughey** [Azure/Enterprise-Scale#1265] opened 2023-03-22 19:34 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: v1.3.7

**azure provider**: azurerm

**module**: archetypes

#### Describe the bug

The "effect" parameter appears to have been missed in the policyDefinitionReferenceId block for RecoveryVaultDeployDiagnosticLogDeployLogAnalytics in the policy set definition JSON code:

/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json

lines 1625-1636

#### Screenshots

![image](https://user-images.githubusercontent.com/122932140/227016617-9474fdb6-a768-4b97-9369-8b3ad0e54d85.png)

**Comment by matt-FFFFFF** [comment] 2023-03-29 12:27
Hi @JoshuaMcConnaughey it seems the parameter is not present in the built-in definition

https://portal.azure.com/#view/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fc717fb0c-d118-4c43-ab3d-ece30ac81fb3

**Comment by JoshuaMcConnaughey** [comment] 2023-03-29 15:27
Hello @matt-FFFFFF - thank you for getting back to me!

The Enterprise-Scale initiative that deploys this policy has a parameter for "Effect" that is used by every policy in the initiative except this Recovery Vault policy that I called out in my initial post. The initiative is a combination of Custom and Built-in policies. For consistent behavior of the "Effect" parameter across all the intiative's policies, I would recommend that this Recovery Vault policy be replaced with a custom version of the built-in policy with the "Effect" parameter incorporated.

The screenshot below illustrates how this policy alone does not receive the "Effect" parameter from the initiative:

![image](https://user-images.githubusercontent.com/122932140/228587355-c50987b1-2e60-491b-96b3-c41a19f7ec1e.png)

**Comment by jtracey93** [comment] 2023-03-29 15:41
Thanks Both, we really would prefer to avoid creating customs if we can avoid it and instead get the owners of the built-in definitions to fix/enhance their policy.

Looping in @paulgrimley can we get this tracked in ADO and then maybe one to raise to your contact in the backup/ASR PG as an ask?

**Comment by paulgrimley** [comment] 2023-03-29 18:14
AB#27602 assigned to @Springstone to pursue - note as this is built-in owned by BCDR team we are reliant on them for timescales to fix this so please do not expect a rapid turnaround on this as it is not a bug as such.

**Comment by JoshuaMcConnaughey** [comment] 2023-03-30 13:37
Thank you Paul!

**Comment by Springstone** [comment] 2023-04-03 17:13
Minor update: the discrepancy has been acknowledged and is being investigated. As Paul mentioned it will likely take some time for this to be addressed.

**Comment by paulgrimley** [comment] 2023-04-12 12:25
@JoshuaMcConnaughey I've had confirmation that this will be looked at in this semester of work that the BCDR team have planned as they are the policy owners / authors which will be by end of September latest - these timelines are out of our hands unfortunately. cc: @Springstone

**Comment by Springstone** [comment] 2024-07-04 13:47
As we've deprecated all ALZ diagnositc settings policies in favor of the new Diagnostic Settings v2 initiatives. The new initiatives (including what we deploy now in ALZ) cover 140+ Azure resources, including ASR and the multiple vaults. As there is no further action required from this team, will be closing this issue.

**Closed by Springstone** 2024-07-04 13:47 UTC
Labels: policy, engineering, Area: Diagnostic Settings
