### ISSUE TITLE
Bug Report: Diagnostic policies look for a hardcoded named resource

### ISSUE THREAD

**Issue by anwather** [Azure/Enterprise-Scale#1060] opened 2022-09-28 07:55 UTC
<p>Diagnostic policies look for a hardcoded named resource. The name <code>setByPolicy</code> is hardcoded in the conditions for each diagnostic DINE policy. </p>

**Comment by anwather** [comment] 2022-09-28 07:57
#1059

**Comment by jfaurskov** [comment] 2022-10-07 13:11
Closing as this is a duplicate of #478. PR for fix is in the works here #1059

**Closed by jfaurskov** 2022-10-07 13:11 UTC
Labels: bug, policy, Needs: Triage :mag:
