### ISSUE TITLE
"Configure diagnostic settings for Table Services to Log Analytics workspace" built-in policy unexpected behavior

### ISSUE THREAD

**Issue by shiweizhang0529** [Azure/Enterprise-Scale#1203] opened 2023-02-07 10:35 UTC
**Issue Description:**

For built-in policy "Configure diagnostic settings for Table Services to Log Analytics workspace", it will mark all the blob storage account as non-compliant no matter how many times we run remediation tasks. 

Policy definition: /providers/Microsoft.Authorization/policyDefinitions/2fb86bf3-d221-43d1-96d1-2434af34eaa0

Policy set definition: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json#L869 

**Investigation:**

Based on how policy scan works and how this policy definition is written, as we indicate to check resource type "Microsoft.Storage/storageAccounts/tableServices", a collection LIST request will be operated within the policy assignment scope to find all the table service.

As we can see, I have a blob storage called "shiweiblobstorage2" in my environment, and you have the corresponding policy assignment on this resource group
![image](https://user-images.githubusercontent.com/78473081/217220326-58ac8285-f926-4398-9882-85f9550ffc8c.png)

By manually running such LIST table service REST API command (https://learn.microsoft.com/en-us/rest/api/storagerp/table-services/list?tabs=HTTP#code-try-0) on this blob storage, we actually can find a table service called "default":
![image](https://user-images.githubusercontent.com/78473081/217219545-1666fbfd-d6d4-404f-b723-ddca2f34786b.png)

And since this List operation does return a table service, the built-in policy will consider the condition in If section is met and therefore this Blob Storage will show up in the compliance result.

Then, since Blob Storage can pass the condition in If section, Policy engine will check whether there is any diagnostic setting on this table service called “default”. 

However, if we try to use REST API to get such table service manually (https://learn.microsoft.com/en-us/rest/api/storagerp/table-services/get-service-properties?tabs=HTTP#code-try-0), we get below error and cannot get the table service.
![image](https://user-images.githubusercontent.com/78473081/217209780-0acc52bd-128e-432c-893b-0355d9ea957d.png)

As the result, the Policy engineer cannot find diagnostic setting from this table service, and therefore existenceCondition returns false and the Blob Storage will be marked as non-compliant. Even if we try to manually create a remediation task to make to compliant, since the corresponding table service is not reachable as we see above, the deployment of diagnostic setting will eventually fail and the Blob Storage will still be non-compliant.

**Conclusion:**

To sum up above findings, there is a table service in blob storage; it can be **LIST** but cannot be **GET**. And due to this conflict, such table services are marked as non-compliant by built-in policy "Configure diagnostic settings for Table Services to Log Analytics workspace" forever.

This is kind of a by-design behavior for blob storage, as it still need table service to store metric data from classic diagnostic setting (https://learn.microsoft.com/en-us/azure/storage/common/manage-storage-analytics-logs?tabs=azure-portal): 
![image](https://user-images.githubusercontent.com/78473081/217215538-0ad8ef66-0bdf-4429-8072-cb36b6a13f9b.png)

I have seen post like below that provide some kind of workaround like this:
https://github.com/Azure/Enterprise-Scale/issues/1173
![image](https://user-images.githubusercontent.com/78473081/217219747-a1177aba-e512-4f92-a592-2ad44f1029bb.png)

**Please notice this is not a valid mitigation.** The reason is that every storage account has a table service, and they are all named as "default". Therefore if applying above policy, no table service will be scanned from either blob storage and blob storage, which means this policy becomes useless.

**Concern:**

My customer is using this landing zone and trying to sell it to his clients. According to him, due to this issue, the secure score is always not 100%, which causes concern to this end-client and impact their business.

**Ask:**

We need to see the policy showing the expected result within the landing zone, and we do not think asking customer to change their deployment is a good option. You should consider making the corresponding changes on the repository officially, so that future users will not run into the same issue.

Below are some options we can think of to fix this behavior:
1. For blob storage within the landing zone deployment, manually enabling diagnostic setting on its table service using PowerShell, CLI, REST API and so on: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings?tabs=powershell#create-diagnostic-settings
2. Exclude blob storage from this policy.
3. Remove this built-in policy from the policy set.

**Comment by jtracey93** [comment] 2023-02-07 10:47
Thanks @shiweizhang0529 for the issue and detailed analysis. 

We are already tracking this under #1173 that @matt-FFFFFF and @paulgrimley are working on with the Product Groups for storage.

We want to resolve the root cause of the issue, before amending/removing from initiatives (this is a last resort). As the policy still works for other tables etc. on the storage account, which is value to the customers.

Appreciate the frustration and we are working with PG teams internally to come to a resoultion.

I will close this issue as a duplicate so we can track in #1173 going forward.

**Closed by jtracey93** 2023-02-07 10:47 UTC
Labels: bug, Needs: Triage :mag:

**Comment by shiweizhang0529** [comment] 2023-02-07 11:15
Hi @jtracey93 , thanks for the reply. Glad to know that you have already discussed this issue with storage PG, and I really appreciate you sharing the update with us. 

At the same time, as I mentioned in above post, the mitigation provided in https://github.com/Azure/Enterprise-Scale/issues/1173 is not a valid solution due to reason mentioned above. And in case our customers get confused by it, I guess we should state clearly in issue 1173 that this is not something working
