### ISSUE TITLE
Bug Report: # Deploy policy initiative for preventing usage of public endpoint for Azure PaaS services fails

### ISSUE THREAD

**Issue by maxgaulhofer** [Azure/Enterprise-Scale#1062] opened 2022-09-28 08:45 UTC
<p><strong>Describe the bug</strong> </p>
<p>The file <code>.\eslzArm\managementGroupTemplates\policyDefinitions\DENY-PublicEndpointsPolicySetDefinition.json</code> does not exist in the repository. Possibly the documentation is not up-to-date. </p>
<p>When deploying Policy 2 </p>
<p><strong>Steps to reproduce</strong> </p>
<p>1. </p>
<pre><code>$ESLZPrefix = &quot;ESLZ&quot;
$Location = &quot;westeurope&quot;
$DeploymentName = &quot;EntScale&quot;
$TenantRootGroupId = (Get-AzTenant).Id
$SecurityContactEmailAddress = &quot;&lt;replace@this.address&gt;&quot;
$CorpConnectedLandingZoneSubscriptionId = &quot;&lt;replace me&gt;&quot; 
$OnlineLandingZoneSubscriptionId = &quot;&lt;replace me&gt;&quot;

New-AzManagementGroupDeployment -Name &quot;$($DeploymentName)-policy2&quot; `
                                -ManagementGroupId $ESLZPrefix `
                                -Location $Location `
                                -TemplateFile .\eslzArm\managementGroupTemplates\policyDefinitions\README.md `
                                -Verbose
</code></pre>
<p><code>
C:\dev\Enterprise-Scale [main ≡]&gt;               New-AzManagementGroupDeployment -Name &quot;$($DeploymentName)-policy2&quot;</code>
                                -ManagementGroupId $ESLZPrefix <code>
                                -Location $Location</code>
                                -TemplateFile .\eslzArm\managementGroupTemplates\policyDefinitions\DENY-PublicEndpointsPolicySetDefinition.json `
                                -Verbose
New-AzManagementGroupDeployment : Cannot retrieve the dynamic parameters for the cmdlet. Cannot find path 'C:\dev\Enterprise-Scale\eslzArm\managementGroupTemplates\policyDefinitions\DENY-PublicEndpointsPolicySetDefinition.json' because it does not exist.
At line:1 char:15 </p>
<ul>
<li>…             New-AzManagementGroupDeployment -Name &quot;$($DeploymentName) … </li>
<li>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~<ul>
<li>CategoryInfo          : InvalidArgument: (:) [New-AzManagementGroupDeployment], ParameterBindingException </li>
<li>FullyQualifiedErrorId : GetDynamicParametersException,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureManagementGroupDeploymentCmdlet </li> </ul> </li>
</ul>
<p><img src="https://user-images.githubusercontent.com/6785359/192733415-2ed9f75b-1b19-4ba2-9455-8598b60cb947.png" alt=afbeelding> </p>
<p><strong>Screenshots</strong> </p>

**Comment by jtracey93** [comment] 2022-09-28 10:54
Hey @maxgaulhofer,

Can i suggest you use the ALZ-Bicep modules instead as the ARM side of ALZ is mainly built to support the Portal Experience and isnt super friendly (as you are seeing) for deploying manually via ARM deployments (by design).

The ALZ-Bicep modules I think you will be interested in are:

- https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/definitions
- https://github.com/Azure/ALZ-Bicep/tree/main/infra-as-code/bicep/modules/policy/assignments/alzDefaults

Let us know how you get on

Thanks

Jack

**Closed** 2022-09-28 16:24 UTC
Labels: bug, policy, Needs: Author Feedback
