### ISSUE TITLE
Policy assignment - Configure Azure PaaS services to use private DNS zones - missing policies for many paas services

### ISSUE THREAD

**Issue by endreigesund** [Azure/Enterprise-Scale#1097] opened 2022-10-27 11:14 UTC
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.3.2

**azure provider**: latest

**module**: 2.4.1

The module deployes central private dns zones for azure-paas-privaete endpoints in the connectivity subscription. 
Developers that deploy workloads in our landing-zones are told to not use public endpoints but use private endpoints. 
Expected result from deploying this module was that all deployed endpoints in the "corp" landingzone should get dns-settings configured to use the central private dns zones by policy.

Example of paas-service not getting this by policy:
-SQL Server
-Storage accounts
-App service slots
-etc.

Because of this the dev-teams need to configure this manually or from devops by their serviceconnection but then they must have the Contributor role on the central dns zones and that is not desired.

The desired state is documented here:
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/private-link-and-dns-integration-at-scale
and according to this - a lot more policies are needed:
https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns#azure-services-dns-zone-configuration

At least there should be a 1:1 match between the zones the module creates and those policy-assignments.

**Reproduce issue:**
Deploy the module with core, connectivity resources and corp landing zone. 
Deploy a SQL Server in the landing zone with private endpoint - the endpoint doesn't get registered in the dns-zone in connectivity.

Deployed policies
![image](https://user-images.githubusercontent.com/22214517/198267416-9dc9c549-03b7-4604-b537-90a136d44abf.png)

**Comment by jtracey93** [comment] 2022-10-27 13:50
Thanks @endreigesund (& @krowlandson) we are indeed working on this in November's sprint for ALZ/ESLZ to work out how big the gap is and what built-ins already exist that we can add to this initiative and then work with PGs to address the gaps.

Im going to close this one as its a duplicate of #725 which we will track this in 👍

**Closed by jtracey93** 2022-10-27 13:50 UTC
Labels: Needs: Triage :mag:
