### ISSUE TITLE
Feature Request: Update Deploy-Diagnostics-LogAnalytics Policy_Set

### ISSUE THREAD

**Issue by birdnathan** [Azure/Enterprise-Scale#1067] opened 2022-10-04 14:59 UTC
<h3 id=communitynote>Community Note </h3>

<ul>
<li>Please vote on this issue by adding a &#128077; <a href="https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/">reaction</a> to the original issue to help the community and maintainers prioritize this request </li>
<li>Please do not leave &quot;+1&quot; or &quot;me too&quot; comments, they generate extra noise for issue followers and do not help prioritize the request </li>
<li>If you are interested in working on this issue or have submitted a pull request, please leave a comment </li>
</ul>

<h3 id=description>Description </h3>
<h4 id=isyourfeaturerequestrelatedtoaproblem>Is your feature request related to a problem? </h4>
<p>This <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/main/modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diagnostics_loganalytics.tmpl.json">policy<em>set</em>definition</a> contains a reference to a now deprecated policy - 6f8f98a4-f108-47cb-8e98-91a0d85cd474 </p>
<h4 id=describethesolutionyoudlike>Describe the solution you'd like </h4>
<p>Can this be updated to reference the new storage account policies? </p>
<p>storage accounts (id: /providers/Microsoft.Authorization/policyDefinitions/59759c62-9a22-4cdf-ae64-074495983fef), blob services (b4fe1a3b-0715-4c6c-a5ea-ffc33cf823cb), file (25a70cc8-2bd4-47f1-90b6-1478e4662c96), queue (7bd000e3-37c7-4928-9f31-86c4b77c5c45), and table (2fb86bf3-d221-43d1-96d1-2434af34eaa0). </p>

**Comment by jtracey93** [comment] 2022-10-04 15:17
Thanks @birdnathan for the issue. 

I believe this is a duplicate of #1034 so closing this one and tracking under #1034 

We are just about to embark on a number of policy updates so will add this to the list 👍
CC: @paulgrimley

**Closed by jtracey93** 2022-10-04 15:17 UTC
Labels: policy
