### ISSUE TITLE
Update parameter syntax for the effect 

### ISSUE THREAD

**Issue by shballa-msft** [Azure/Enterprise-Scale#948] opened 2022-04-06 10:55 UTC
https://github.com/Azure/Enterprise-Scale/blob/83f7e5566db7ed2971120e707a71d76df440c72f/eslzArm/managementGroupTemplates/policyDefinitions/policies.json#L11239

**Comment by jtracey93** [comment] 2022-04-06 11:30
Hi @shballa-msft,

Can you provide some more context/information here please?

Thanks

Jack

**Comment by shballa-msft** [comment] 2022-04-06 11:37
Hello @jtracey93 
"effect": "[parameters('effect')]" 

Please update the value as above

**Comment by shballa-msft** [comment] 2022-04-06 11:38
I also observe that the Deny affect for this Custom Policy  "Web Application should only be accessible over HTTPS" is not working 
. i think it will work as DINE policy only. please check

**Comment by jtracey93** [comment] 2022-04-06 11:46
Hey @shballa-msft,

This is correct due to ARM function escaping (https://docs.microsoft.com/azure/azure-resource-manager/templates/template-expressions) that is required for the policy deployment.

When it is processed by ARM the first `[` is removed, due to the way these templates are authored, and it is correctly set in the policy definition once deployed, as shown below:
![image](https://user-images.githubusercontent.com/41163455/161967644-c8ac9e41-cbd4-4330-bd3d-c54fcdb2d5aa.png)

Therefore I will close this issue as this is not an issue and is by design 👍

Thanks

Jack

**Closed by jtracey93** 2022-04-06 11:46 UTC
Labels: wontfix

**Comment by shballa-msft** [comment] 2022-04-06 13:06
Thank jack
