### ISSUE TITLE
Conflict when deploying Contoso with VPN Gateway

### ISSUE THREAD

**Issue by magnethy** [Azure/Enterprise-Scale#355] opened 2020-12-16 09:43 UTC
**Describe the bug**
When deploying the full contoso ref. impl. the deploy fails with the following error

```
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "Conflict",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"DeploymentFailed\",\r\n        \"message\": \"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\",\r\n        \"details\": [\r\n          {\r\n            \"code\": \"Conflict\",\r\n            \"message\": \"{\\r\\n  \\\"status\\\": \\\"Failed\\\",\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"ResourceDeploymentFailure\\\",\\r\\n    \\\"message\\\": \\\"The resource operation completed with terminal provisioning state 'Failed'.\\\",\\r\\n    \\\"details\\\": [\\r\\n      {\\r\\n        \\\"code\\\": \\\"DeploymentFailed\\\",\\r\\n        \\\"message\\\": \\\"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.\\\",\\r\\n        \\\"details\\\": [\\r\\n          {\\r\\n            \\\"code\\\": \\\"Conflict\\\",\\r\\n            \\\"message\\\": \\\"{\\\\r\\\\n  \\\\\\\"status\\\\\\\": \\\\\\\"Failed\\\\\\\",\\\\r\\\\n  \\\\\\\"error\\\\\\\": {\\\\r\\\\n    \\\\\\\"code\\\\\\\": \\\\\\\"ResourceDeploymentFailure\\\\\\\",\\\\r\\\\n    \\\\\\\"message\\\\\\\": \\\\\\\"The resource operation completed with terminal provisioning state 'Failed'.\\\\\\\",\\\\r\\\\n    \\\\\\\"details\\\\\\\": [\\\\r\\\\n      {\\\\r\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"OperationFailureErrors\\\\\\\",\\\\r\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"The operation failed due to following errors: '[\\\\\\\\\\\\\\\"The operation failed due to following errors: '[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"The vpn gateway deployment operation failed due to an intermittent error. Please try again.\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"]'.\\\\\\\\\\\\\\\"]'.\\\\\\\",\\\\r\\\\n        \\\\\\\"details\\\\\\\": []\\\\r\\\\n      }\\\\r\\\\n    ]\\\\r\\\\n  }\\\\r\\\\n}\\\"\\r\\n          }\\r\\n        ]\\r\\n      }\\r\\n    ]\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"
            }
        ]
    }
}
```

I've tried rerunning the deployment again, 10-12 hours later, with the same parameters, resulting in the same error.

If I go to the Connectivity subscription's "EntScale connectivitySub" deployment I can see that it fails on Microsoft.Network/azureFirewalls BadRequest:

```
{
    "status": "Failed",
    "error": {
        "code": "SimultaneousAddDeleteNotPermittedForHubIPAddress",
        "message": "Addition and deletion of Public IP addresses not permitted in a single operation for Azure Firewall /subscriptions/63dcfd64-4289-4ef8-afb7-ce97df63278d/resourceGroups/test--connectivity/providers/Microsoft.Network/azureFirewalls/test--fw-westeurope.",
        "details": []
    }
}
```

I can't say for sure if this exact error occurred on the first run, but I have a slight suspicion it was not.

**Steps to reproduce**

1. Deploy contoso ref. impl. with all options enabled (including VPN Gateway)

**Screenshots**
![main-deployment](https://user-images.githubusercontent.com/47104/102331469-30671c80-3f8b-11eb-8e88-07357b8a992f.png)

![fw](https://user-images.githubusercontent.com/47104/102331489-352bd080-3f8b-11eb-9eee-de23909271df.png)

**Comment by krnese** [comment] 2020-12-16 13:50
Thanks for reporting this. It appears to be caused by a race condition on the networking resource provider, so we will correct that with a PR.

If this is for testing purposes, I suggest using Adventure Works (traditional hub and spoke networking) for now until we have patched Contoso.

**Comment by krnese** [comment] 2020-12-21 20:16
Closing this as we have corrected the issue in Contoso reference implementation. Thanks!

**Closed by krnese** 2020-12-21 20:16 UTC
Labels: bug, triage
